---
title: "CES Elasticity"
---

```{r}
source("Utility Maximization.R")
```


# Two good
```{r}
df <- read.csv("./Data Files/Quiz01_Q22_s.csv")

mod = lm(log(x1/x2) ~ log(w1/w2), data = df)
```
```{r}
plot(log(df$w1/df$w2), log(df$x1/df$x2)) + abline(mod)
```

```{r}
sigma = round(-mod$coefficients[2], 3)
sigma
```
```{r}
x = c(19, 12)
w = c(1, 1)

x_sigma = x^(1/sigma)

a = x_sigma*w / sum(x_sigma*w)
a
```
```{r}
scenarios = list(
  c(1.11, 0.96, 33.79),
  c(0.97, 1.06, 26.35),
  c(0.93, 1.17, 35.03),
  c(1.05, 1.15, 25.73)
)#w1, w2, w3, M

for (scenario in scenarios){
  print("New Scenario")
print(ces_two_good_umax(
  1,
  sigma,
  a[1],
  a[2],
  scenario[1],
  scenario[2],
  scenario[3]
))
}
```

# Three good

```{r}
library(glue)
df <- read.csv("./Data Files/Quiz01_Q23_s.csv") # Step 1 - Edit the file path
```


```{r} 
# Run this entire cell without editing
opts = list(
  c("x1", "w1"),
  c("x2", "w2"),
  c("x3", "w3")
)

for (i in 1:3) {
opt_a = opts[[i]]
opts_iter = opts[-i]
opt_b = opts_iter[[1]]
opt_c = opts_iter[[2]]

print(glue("Calibration holding {opt_a[1]} and {opt_a[2]}"))
  
  iter_df <- data.frame(
    rep(df[[opt_a[1]]], 2),
    rep(df[[opt_a[2]]], 2),
    c(df[[opt_b[1]]], df[[opt_c[1]]]),
    c(df[[opt_b[2]]], df[[opt_c[2]]]),
    c(rep(0, nrow(df)), rep(1, nrow(df)))
  )
  
  names(iter_df) = c(opt_a, "xn", "wn", "dummy")
  
  mod = lm(log(eval(parse(text = opt_a[1]))/xn) ~ log(eval(parse(text = opt_a[2]))/wn) + dummy, data = iter_df)
  sigma = round(-mod$coefficients[2], 3)
  print(glue("sigma_{i} = {sigma}"))
  print(glue("standard error = {summary(mod)$coefficients[2, 2]}"))
}
```
# Pick the sigma with the smolest standard error

```{r}
sigma = 0.841 # Pick the sigma with the smallest standard error
```


```{r}
x = c(8, 13, 17) # Step 3 - Edit these two things as usual
w = c(1, 1, 1)

x_sigma = x^(1/sigma)

a = x_sigma*w / sum(x_sigma*w)
a
```
```{r}
# Step 4 - Edit the scenarios
scenarios = list( 
  c(0.92, 1, 0.9, 40.66),
  c(1.04, 1.08, 1.09, 44.08),
  c(0.86, 0.96, 1.04, 33.82),
  c(1.05, 1.01, 0.94, 39.9)
)#w1, w2, w3, M

for (scenario in scenarios){
  print("New Scenario")
print(ces_three_good_umax(
  1,
  sigma,
  a[1],
  a[2],
  a[3],
  scenario[1],
  scenario[2],
  scenario[3],
  scenario[4]
))
}
```

