---
title: "Non Market Valuation"
---

# Exploratory analysis - Easier to just use the filters in the data viewer

```{r}
df = read.csv("./Data Files/Quiz01_Q24_s.csv")
df$chosen = (df$ChosenAlternative == df$Alternative)
```

# Fitting logit model

```{r}
library(mlogit)
library(glue)
```
```{r}
df = read.csv("./Data Files/Quiz01_Q25_s.csv")
df$chosen = (df$ChosenAlternative == df$Alternative)

df$choiceID = (df$ID - 1)*5 + df$ChoiceSet
```

```{r}
log_data = mlogit.data(df, choice = "chosen", shape = "long", chid.var = "choiceID", alt.var = "Alternative")

mod1 = mlogit(chosen~Weed + Crawl + Fly + Cost| -1, data = log_data)
```

```{r}
summary(mod1)
```

```{r}
coefs = coef(mod1)
v_cv = vcov(mod1)

coefs
```
$$

se(WTP_{i, cost}) = \frac{1}{\beta_{cost}} * \sqrt{var(\beta_i) - 2*WTP*cov(\beta_{cost}, \beta_i) + WTP^2 * var(\beta_{cost})} 

$$
$$

se(WTP_{i, cost}) = \frac{1}{coef[4]} * \sqrt{v\_cv[i, i] - 2*WTP*v\_cv[i, 4] + WTP^2 * v\_cv[4, 4]} 

$$
```{r}
se_wtp <- function(i, wtp) {
  return (1/coefs[4] * sqrt(v_cv[i, i] - 2 * wtp * v_cv[i, 4] + wtp^2 * v_cv[4, 4]))
} 
```


```{r}
for (i in 1:3) {
  print(coefs[i])
  
  wtp = coefs[i]/coefs[4]
  
  print(glue("WTP = {wtp}"))
  
  se = se_wtp(i, wtp)
  
  print(glue("SE = {se}"))
}
```
## Hypothesis testing

```{r}
mod2 = mlogit(chosen ~ Weed + Crawl + Fly + Cost + I(Weed*F) + I(Crawl*F) + I(Fly*F)|-1,data = log_data)

summary(mod2)
```

```{r}
library(lmtest)
```
> lrtest(unconstrained_model, constrained_model)

```{r}
lrtest(mod2, mod1)
```

