---
title: "Utility Maximization and Expenditure Minimization"
---

```{r}
source("Utility Maximization.R")
source("Expenditure Minimization.R")
```
# Cobb Douglas

## 2 Good

```{r}
# Options
  #c(w1, w2, M),
  #c(2, 4, 2),
  #c(3, 5, 5),
  #c(2, 6, 10)

options = list(
  c(1, 2, 5),
  c(2, 4, 2),
  c(3, 5, 5),
  c(2, 6, 10)
)

for (option in options){
  print("New Scenario")
print(cobb_douglas_two_good_umax(
  A = 1,
  a1 = 0.75,
  a2 = 0.25,
  w1 = option[1],
  w2 = option[2],
  M = option[3]
)
)
  }

```
## 3 Good

```{r}
options = list(
  c(1, 2, 3, 5),
  c(1, 2, 3, 5),
  c(1, 2, 3, 5),
  c(1, 2, 3, 5)
)

for (option in options){
  print("New Scenario")
  print(
cobb_douglas_three_good_umax(
  A = 1,
  a1=0.75,
  a2=0.1,
  a3=0.15,
  w1=option[1],
  w2=option[2],
  w3=option[3],
  M=option[4]
)
)
}
```
# CES
## 2 Good
```{r}
# Options
  #c(w1, w2, M),
  #c(2, 4, 2),
  #c(3, 5, 5),
  #c(2, 6, 10)
options = list(
  c(1, 2, 5),
  c(2, 4, 2),
  c(3, 5, 5),
  c(2, 6, 10)
)

for (option in options){
print("New Scenario")
  print(
  ces_two_good_umax(
  A = 1,
  sigma = 0.83,
  a1 = 0.33,
  a2 = 0.67,
  w1 = option[1],
  w2 = option[2],
  M = option[3]
)
)
}
```

```{r}
ces_three_good_umax(
  A = 1,
  sigma = 0.74,
  a1 = 0.33,
  a2 = 0.4,
  a3 = 0.27,
  w1 = 5,
  w2 = 8,
  w3 = 6,
  M = 56
)
```

```{r}
cobb_douglas_two_good_emin(
  A = 1,
  a1 = 0.2,
  a2 = 0.8,
  w1 = 6,
  w2 = 7,
  U = 77
)
```

```{r}
cobb_douglas_three_good_emin(
  A = 1,
  a1 = 0.25,
  a2 = 0.5,
  a3 = 0.25,
  w1 = 8,
  w2 = 6,
  w3 = 8,
  U = 66
)
```

```{r}
ces_two_good_emin(
  A = 1,
  sigma = 1.09,
  a1 = 0.2,
  a2 = 0.8,
  w1 = 5,
  w2 = 5,
  U = 78
)
```

```{r}
ces_three_good_emin(
  A = 1,
  sigma = 1.08,
  r = 1 - 1/sigma,
  a1 = 0.25,
  a2 = 0.5,
  a3 = 0.25,
  w1 = 8,
  w2 = 6,
  w3 = 8,
  U = 66
)
```
