###########################################################################
# ADVANCED APPLIED MICROECONOMICS IDEC8064
# Topic 1: Consumer behavior and welfare analysis
# R example 03
# Crawford School of Public Policy - The Australian National University
# Lecturer: Professor Long Chu
###########################################################################


 ################################################
 # Non-market valuation
 ################################################

    # Close all graphics, clear memory and screen
    graphics.off(); remove(list=ls());cat("\14");
    
    
    # Install mlogit package (only if you haven't done so)
    #install.packages("mlogit")

    # Load mlogit package
    library("mlogit")

    # Load data from CSV and store in CM object
    Ex0103<-read.csv("Example_0103_data.csv")

    # Extract (and display) the choice 5 of the 200th respondent
    Res200Choice5=Ex0103[(Ex0103$id==200)&(Ex0103$ChoiceSet==5),]
    # Calculate the expected utility generated by the three attributes 
    R200C5U1=0.059*Res200Choice5[1,"Wetland"]+ 0.512*Res200Choice5[1,"Bird"]+ 0.519*Res200Choice5[1,"Fish"]+(-0.621)*Res200Choice5[1,"Cost"]
    R200C5U2=0.059*Res200Choice5[2,"Wetland"]+ 0.512*Res200Choice5[2,"Bird"]+ 0.519*Res200Choice5[2,"Fish"]+(-0.621)*Res200Choice5[2,"Cost"]
    R200C5U3=0.059*Res200Choice5[3,"Wetland"]+ 0.512*Res200Choice5[3,"Bird"]+ 0.519*Res200Choice5[3,"Fish"]+(-0.621)*Res200Choice5[3,"Cost"]
    # We do calculate the utility step by step here for illustration purpose (It can be faster and shorter if you use matrix multiplication)
    
    # Extract (and display) the choice 1 of the 2nd respondent
    Res2Choice1=Ex0103[(Ex0103$id==2)&(Ex0103$ChoiceSet==1),]
    # Calculate the expected utility generated by the three attributes 
    R2C1U1=0.059*Res2Choice1[1,"Wetland"]+ 0.512*Res2Choice1[1,"Bird"]+ 0.519*Res2Choice1[1,"Fish"]+(-0.621)*Res2Choice1[1,"Cost"]
    R2C1U2=0.059*Res2Choice1[2,"Wetland"]+ 0.512*Res2Choice1[2,"Bird"]+ 0.519*Res2Choice1[2,"Fish"]+(-0.621)*Res2Choice1[2,"Cost"]
    R2C1U3=0.059*Res2Choice1[3,"Wetland"]+ 0.512*Res2Choice1[3,"Bird"]+ 0.519*Res2Choice1[3,"Fish"]+(-0.621)*Res2Choice1[3,"Cost"]


    # Generate unique ID for each situation where a choice is made.
    Ex0103$ChoiceID<-(Ex0103$id-1)*6+Ex0103$ChoiceSet
    
    # Generate a dummy variable for each alternative (1=selected, 0=non-selected)
    Ex0103$ChoiceYesNo<-(Ex0103$Alt==Ex0103$Choice)
    
    # Generate a new dataset in which R knows what is what
    mlogitdata<-mlogit.data(Ex0103,choice="ChoiceYesNo",shape="long",chid.var="ChoiceID",alt.var="Alt")

    # Eetimate the baseline specification, store the result in object 'baseline' and display it
    baseline<-mlogit(ChoiceYesNo~Wetland+Bird+Fish+Cost|+0,data=mlogitdata); summary(baseline)

    # Store the variance-covariance matrix in object V and display it
    V<-vcov(baseline); V

    # Store the coefficient vector in object betahat and display it
    betahat<-coef(baseline); betahat;

    # Calculate the WTP for Wetland and its standard error (using Delta method) manually
    WTP_Wetland_Manual=-0.059295/(-0.6208694); WTP_Wetland_Manual;
    se_WTP_Wetland_Mannual=sqrt(1/(-0.62084694)^2*(0.0001934934-2*0.059295/(-0.6208694)*(-0.0007018273)+(0.059295/(-0.6208694))^2*0.0043723126)); se_WTP_Wetland_Mannual

    # Calculate the standard error of the WTP using the estimate notations
    se_WTP_Wetland<- sqrt(1/betahat[[4]]^2*(V[1,1]-2*betahat[[1]]/betahat[[4]]*V[1,4]+(betahat[[1]]/betahat[[4]])^2*V[4,4]));se_WTP_Wetland

    # Add Age into the baseline specification, display the result (without storing it)
    summary(mlogit(ChoiceYesNo~Wetland+Bird+Fish+Cost+Age|+0,data=mlogitdata)); 

    # Test for WTP and Age
    summary(mlogit(ChoiceYesNo~Wetland+Bird+Fish+Cost+I(Age*Cost)|+0,data=mlogitdata));

    # Test for WTP and beig a farmer
    summary(mlogit(ChoiceYesNo~Wetland+Bird+Fish+Cost+I(Cost*(Occupation==2))|+0,data=mlogitdata));
    

  